server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:h2:~/test 
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  profiles:
    active:
    - posting.in-process

hobnob:
  security:
    jwt:
      issuer: hobnob
      secret: hobnob
      time-to-live-in-hours: 168

